# Generated by Django 4.2.21 on 2025-05-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='sent_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
